metadata:
- appName: ''
  dataId: pigeon-config-dev.yml
  desc: 支付模块的全局配置
  group: PAYMENT_GROUP
  type: yaml
- appName: ''
  dataId: pigeon-config-dev.yml
  desc: 网关模块的全局配置
  group: GATEWAY_GROUP
  type: yaml
- appName: ''
  dataId: pigeon-common-dev.yml
  desc: 鸽子框架的共通配置
  group: COMMON_GROUP
  type: yaml
- appName: ''
  dataId: pigeon-config-dev.yml
  desc: 用户中心模块的全局配置
  group: USER_CENTER_GROUP
  type: yaml
- appName: ''
  dataId: pigeon-config-dev.yml
  desc: 订单模块的全局配置
  group: ORDER_GROUP
  type: yaml
- appName: ''
  dataId: seata-server.properties
  desc: seata配置
  group: SEATA_GROUP
  type: properties
